engine_settings:
  time_scale: 1
  target_frame_rate: -1
  capture_frame_rate: 60
behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 10000000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: Project/Assets/Demonstrations/SoccerTwos_12.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: Project/Assets/Demonstrations/SoccerTwos_12.demo
    keep_checkpoints: 5
    max_steps: 50000000
    summary_freq: 20000
    self_play:
      save_steps: 100000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0